### ISSUE TITLE
Add plugin API

### ISSUE THREAD

**Issue by vinnylinck** [FringeLabs/pipefish#36]
API format:
```
.plugin(<object>, <conditional>)
```
Where:
-  __object__: is the webpack plugin object or an object array;
- __conditional__: determines when the plugin will be added or not.

About the conditional:
- *boolean*: evaluate the result of a boolean expression to determine when the plugin is added (or not).

- *function*: run the function and evaluate the result as a boolean to determine if the plugin will be added.

- *string*: try parse the string as a environment variable - *process.env[xxx]* - and if set with any value, it enables the plugin.

- *number*: evaluate the number as a boolean conditional. That means "0" is false and everything else is considered true.

### TO-DO LIST
- [X] add undefined and null support.
- [X] add simple boolean support.
- [X] add function evaluation support.
- [X] add string support.
- [X] add number support.
- [X] add object to array
- [X] validate plugin object type.
- [X] check plugin object interface.
